
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soccer
  template:
    metadata:
      labels:
        app: soccer
    spec:
      containers:
        - name: soccer
          image: 328425174770.dkr.ecr.us-east-1.amazonaws.com/devopsfinalproject:1.1
          ports:
            - containerPort: 80