name: Rust CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set environment variables
        run: |
            echo "DATABASE_URL=your_database_connection_url" >> $GITHUB_ENV
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            
      - name: Install dependencies
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
