name: Rust CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
            echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
            
      - name: Install dependencies
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
